Mike-Mortensen-Portfolio/PubHub_H6_Final

PubHub/PubHub.API/Domain/Entities/Operator.cs
[-] Removed a semicolon in the Operator entity.
=> Removing semicolon in Operator entity.

PubHub/PubHub.Common/Extensions/ServiceExtensions.cs, PubHub/PubHub.Common/Services/BookService.cs, PubHub/PubHub.Common/Services/IBookService.cs, PubHub/PubHub.Common/Services/IPublisherService.cs, PubHub/PubHub.Common/Services/IUserService.cs, PubHub/PubHub.Common/Services/PublisherService.cs, PubHub/PubHub.Common/Services/UserService.cs
Part of #76 
- [+] Added the `PublisherService` which calls the different `PublishersController` API endpoints.
- [~] Modified the `UserService` and `BookService` so that the summaries is on there instead of their interfaces.
=> PublisherService has been added

PubHub/PubHub.API/Controllers/AuthorsController.cs, PubHub/PubHub.API/Controllers/BooksController.cs, PubHub/PubHub.API/Controllers/PublishersController.cs, PubHub/PubHub.API/Controllers/UsersController.cs, PubHub/PubHub.Common/IntegrityConstants.cs, PubHub/PubHub.Common/Models/Authors/AuthorCreateModel.cs, PubHub/PubHub.Common/Models/Authors/AuthorInfoModel.cs, PubHub/PubHub.Common/Models/Books/BookInfoModel.cs
I've added a new controller with endpoints the supports authers.
- Get collection
- Get single
- Add
- Delete
This closes #100
=> Added author controller

PubHub/PubHub.API/Controllers/AuthorsController.cs, PubHub/PubHub.Common/Extensions/ServiceExtensions.cs, PubHub/PubHub.Common/Services/AuthorService.cs, PubHub/PubHub.Common/Services/BookService.cs, PubHub/PubHub.Common/Services/IAuthorService.cs
Closes #104 
- Added the `AuthorService` and added it to the `ServiceExtension` adding the scoped instance.
- Corrected a typo in one of the error responses in the `BookService`.
- Corrected a typo in the `AuthorController` to be singular instead of plural with it returning only one model.
=> Author services added

PubHub/PubHub.Common/Services/AuthorService.cs, PubHub/PubHub.Common/Services/BookService.cs, PubHub/PubHub.Common/Services/PublisherService.cs, PubHub/PubHub.Common/Services/UserService.cs
Closes #115 
- Implementing a more simpler way of returning the empty list if it ends up in the catch block of the try-catch.
=> Change return types on Empty lists.

PubHub/PubHub.Common/Extensions/ServiceExtensions.cs, PubHub/PubHub.Common/Services/ContentTypeService.cs, PubHub/PubHub.Common/Services/IContentTypeService.cs
Closes #105 
- Added the `ContentTypeService` corresponding to the `ContentTypeController`.
=> ContentTypeService added

PubHub/PubHub.API/Controllers/AuthController.cs, PubHub/PubHub.API/Controllers/AuthorsController.cs, PubHub/PubHub.API/Controllers/BooksController.cs, PubHub/PubHub.API/Controllers/GenresController.cs, PubHub/PubHub.API/Controllers/PublishersController.cs, PubHub/PubHub.API/Controllers/UsersController.cs, PubHub/PubHub.API/Domain/Auth/AuthService.cs, PubHub/PubHub.API/Program.cs, PubHub/PubHub.API/PubHub.API.csproj, PubHub/PubHub.API/ServiceExtensions.cs, PubHub/PubHub.API/WebApplicationBuilderExtensions.cs
- Configured Serilog to write to file and console.
- Inject `ILogger<T>` into controllers.
- Log errors.
Closes #107.
=> Add Serilog to API project

PubHub/PubHub.AdminPortal/Program.cs, PubHub/PubHub.BookMobile/MauiProgram.cs, PubHub/PubHub.BookMobile/PubHub.BookMobile.csproj, PubHub/PubHub.BookWeb/Program.cs, PubHub/PubHub.BookWeb/PubHub.BookWeb.csproj, PubHub/PubHub.Common/ApiService/ApiConstants.cs, PubHub/PubHub.Common/ApiService/ApiOptions.cs, PubHub/PubHub.Common/ApiService/ServiceRoot.cs, PubHub/PubHub.Common/Extensions/ServiceExtensions.cs, PubHub/PubHub.Common/PubHub.Common.csproj, PubHub/PubHub.Common/Services/AuthenticationService.cs, PubHub/PubHub.Common/Services/AuthorService.cs, PubHub/PubHub.Common/Services/BookService.cs, PubHub/PubHub.Common/Services/ContentTypeService.cs, PubHub/PubHub.Common/Services/GenreService.cs, PubHub/PubHub.Common/Services/HttpClientService.cs, PubHub/PubHub.Common/Services/IBookService.cs, PubHub/PubHub.Common/Services/IHttpClientService.cs, PubHub/PubHub.Common/Services/PublisherService.cs, PubHub/PubHub.Common/Services/UserService.cs
- Replaced `HttpClientFactory` with `HttpClientService`.
- Implemented Polly retries.
- Added `ConfigureForMobile` property in `ApiOptions`.
Closes #10.
=> HttpClientService with Polly

PubHub/PubHub.API/Controllers/AuthController.cs, PubHub/PubHub.API/Controllers/PublishersController.cs, PubHub/PubHub.API/Controllers/UsersController.cs, PubHub/PubHub.API/Domain/Extensions/PubHubContextExtensions.cs, PubHub/PubHub.API/ServiceExtensions.cs, PubHub/PubHub.Common/Models/Accounts/AccountCreateModel.cs, PubHub/PubHub.Common/Models/Accounts/UserCreatedResponseModel.cs
- Remove `AddUserAsync` from the `UsersController`.
- Register users via the "/user" endpoint on the `AuthController`.
- Register publishers using the `PublisherController`.
Addresses part of #132.
=> Register accounts

PubHub/PubHub.AdminPortal/Components/Auth/Login.razor, PubHub/PubHub.AdminPortal/Components/Models/AccountForm.cs, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor, PubHub/PubHub.Common/PubHub.Common.csproj, PubHub/PubHub.Common/Services/AuthenticationService.cs, PubHub/PubHub.Common/Services/ErrorResponse.cs
- Small fixes regarding warnings being thrown about a Microsoft.AspNet.Mvc Nuget package that caused a ton o warnings to appear.
- The remaining warning- and message fixes will be added in my next PR.
=> Warning hot fix

PubHub/PubHub.BookMobile/Views/BookInfo.xaml
=> Added publisher to book info view

PubHub/PubHub.AdminPortal/Components/Auth/Login.razor, PubHub/PubHub.AdminPortal/Components/Constants/RegexConstants.cs, PubHub/PubHub.AdminPortal/Components/Constants/ResponseCodeConstants.cs, PubHub/PubHub.AdminPortal/Components/Models/AccountForm.cs, PubHub/PubHub.AdminPortal/Components/Models/BookForm.cs, PubHub/PubHub.AdminPortal/Components/Models/LoginForm.cs, PubHub/PubHub.AdminPortal/Components/Models/PublisherForm.cs, PubHub/PubHub.AdminPortal/Components/Pages/ManagePublishers.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/UpdateBookModal.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor, PubHub/PubHub.AdminPortal/Components/_Imports.razor, PubHub/PubHub.Common/Services/IPublisherService.cs, PubHub/PubHub.Common/Services/PublisherService.cs
Closes #25 
- Input validation on the models and the pages on the admin portal.
- Also added another obsolete as i missed one with the previous PR.
=> Input validation on the Admin portal

PubHub/PubHub.AdminPortal/Components/Auth/Login.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor
- Changes made after the authentication and input validation - tested that everything works again.
=> Changes to Create book after input validation

PubHub/PubHub.BookMobile/App.xaml.cs, PubHub/PubHub.Common/Services/AuthenticationService.cs, PubHub/PubHub.Common/Services/AuthorService.cs, PubHub/PubHub.Common/Services/BookService.cs, PubHub/PubHub.Common/Services/ContentTypeService.cs, PubHub/PubHub.Common/Services/GenreService.cs, PubHub/PubHub.Common/Services/HttpClientService.cs, PubHub/PubHub.Common/Services/IAuthenticationService.cs, PubHub/PubHub.Common/Services/IAuthorService.cs, PubHub/PubHub.Common/Services/IBookService.cs, PubHub/PubHub.Common/Services/IContentTypeService.cs, PubHub/PubHub.Common/Services/IGenreService.cs, PubHub/PubHub.Common/Services/IHttpClientService.cs, PubHub/PubHub.Common/Services/IPublisherService.cs, PubHub/PubHub.Common/Services/PublisherService.cs, PubHub/PubHub.Common/Services/UserService.cs
Closes #162 and closes #66
THis should include the fix for the MAUI Closed Stream problem
=> Fixed the "Closed Stream" issue in services

PubHub/PubHub.AdminPortal/Components/Auth/CustomAuthStateProvider.cs, PubHub/PubHub.AdminPortal/Components/Auth/Login.razor, PubHub/PubHub.AdminPortal/Components/Auth/SignInOrOut.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/CreateBookModal.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Book/RemoveBookModal.razor, PubHub/PubHub.AdminPortal/Components/Pages/Modals/Publisher/CreatePublisherModal.razor
Closes #180 
- Small changes after everything was updated. 
- Also tested that a user now cannot access the admin portal with their login.
=> Small changes to admin portal

PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs, PubHub/PubHub.BookMobile/Views/BookInfo.xaml, PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs
=> Added book summary to BookInfo View

PubHub/PubHub.API/Controllers/BooksController.cs, PubHub/PubHub.API/Domain/Services/TypeLookupService.cs, PubHub/PubHub.API/appsettings.json, PubHub/PubHub.Common/AccessTypeConstants.cs
- Opened up `GetBookAsync()` and `GetBooksAsync()`.
- Added `PurchaseBookAsync()` for purchasing a book as a user.
Closes #179.
=> Purchase books

PubHub/PubHub.BookMobile/App.xaml.cs, PubHub/PubHub.BookMobile/Auth/User.cs, PubHub/PubHub.BookMobile/MauiProgram.cs, PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs, PubHub/PubHub.Common/Models/Accounts/AccountUpdateModel.cs, PubHub/PubHub.Common/PubHub.Common.csproj
=> Replaced Preference storage with secure storage

PubHub/PubHub.BookMobile/Auth/User.cs, PubHub/PubHub.BookMobile/Converters/IsAudiobookConverter.cs, PubHub/PubHub.BookMobile/Converters/IsEbookConverter.cs, PubHub/PubHub.BookMobile/ErrorSpecifications/BadRequestError.cs, PubHub/PubHub.BookMobile/ErrorSpecifications/InvalidTokenError.cs, PubHub/PubHub.BookMobile/ErrorSpecifications/NoConnectionError.cs, PubHub/PubHub.BookMobile/ErrorSpecifications/NotFoundError.cs, PubHub/PubHub.BookMobile/ErrorSpecifications/SetSecureStorageError.cs, PubHub/PubHub.BookMobile/ErrorSpecifications/UnauthorizedError.cs, PubHub/PubHub.BookMobile/ErrorSpecifications/UnproccessableEntityError.cs, PubHub/PubHub.BookMobile/Extensions/ServiceExtensions.cs, PubHub/PubHub.BookMobile/Models/BookListingViewModel.cs, PubHub/PubHub.BookMobile/Models/PageInfo.cs, PubHub/PubHub.BookMobile/StorageConstants.cs, PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/NavigationObject.cs, PubHub/PubHub.BookMobile/ViewModels/PersonalLibraryViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/ProfileViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs, PubHub/PubHub.BookMobile/Views/BookInfo.xaml.cs, PubHub/PubHub.BookMobile/Views/Logout.xaml.cs, PubHub/PubHub.Common/ErrorsCodeConstants.cs
Added better exception handling
Closes #154 and closes #29
=> Added better exception handling

PubHub/PubHub.BookMobile/ViewModels/LibraryViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/LoginViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/ProfileViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/RegisterViewModel.cs, PubHub/PubHub.BookMobile/Views/Library.xaml, PubHub/PubHub.BookMobile/Views/Login.xaml, PubHub/PubHub.BookMobile/Views/Profile.xaml, PubHub/PubHub.BookMobile/Views/Register.xaml
Mobile app should now validate any entry that can cause any problems.
Validation is done on both front end and backend
Closes #24 and it closes #61 because I don't think we have the time to implement fluent validation. If you think I'm wrong. Just let me now (:
=> Added validation

PubHub/PubHub.Common/Extensions/ServiceExtensions.cs, PubHub/PubHub.Common/PubHub.Common.csproj, PubHub/PubHub.Common/Services/HttpClientService.cs
=> Add rate limiter to Polly pipeline

PubHub/PubHub.BookMobile/Auth/User.cs, PubHub/PubHub.BookMobile/ViewModels/BookContentInfoViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/BookInfoViewModel.cs, PubHub/PubHub.BookMobile/ViewModels/EBookViewModel.cs, PubHub/PubHub.BookMobile/Views/EBookView.xaml.cs, PubHub/PubHub.Common/Services/IUserService.cs, PubHub/PubHub.Common/Services/UserService.cs
ALso includes fixes for some build errors on mobile after some prior services changes
Closes #218
=> Book progress can now be persisted on E-Book view
